[workspace]
channels = ["conda-forge"]
name = "HOP_ODF"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
hop-odf = "python src/hop_odf.py"

[dependencies]
python = ">=3.14.3,<3.15"
numpy = ">=2.4.2,<3"
matplotlib = ">=3.10.8,<4"
